#version: "3"
#services:
#  db-master:
#    build:
#      context: ./
#      dockerfile: master/Dockerfile
#
#    restart: always
#    platform: linux/x86_64
#    environment:
#      MYSQL_DATABASE: 'ssgdb'
#      MYSQL_USER: 'user'
#      MYSQL_PASSWORD: '1234'
#      MYSQL_ROOT_PASSWORD: '1234'
#
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#
#    ports:
#      - '3310:3306'
#    container_name: master-db
#    volumes:
#      - my-db-master:/var/lib/mysql
#      - my-db-master:/var/lib/mysql-files
#
#    networks:
#      - net-ssg-mysql
#
#  db-slave:
#    build:
#      context: ./
#      dockerfile: slave/Dockerfile
#
#    restart: always
#    platform: linux/x86_64
#    environment:
#      MYSQL_DATABASE: 'ssgdb'
#      MYSQL_USER: 'user'
#      MYSQL_PASSWORD: '1234'
#      MYSQL_ROOT_PASSWORD: '1234'
#
#    command:
#      - —character-set-server=utf8mb4
#      - —collation-server=utf8mb4_unicode_ci
#
#    ports:
#      - '3311:3306'
#    container_name: slave-db
#    volumes:
#      - my-db-slave:/var/lib/mysql
#      - my-db-slave:/var/lib/mysql-files
#
#    networks:
#      - net-ssg-mysql
#
#volumes:
#  my-db-master:
#  my-db-slave:
#
#networks:
#  net-ssg-mysql:
#    driver: bridge
