server:
  port: 8080

spring:
  application:
    name: SSGPOINT_APP

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
      format_sql: true
    show-sql: true


  datasource:
    url: jdbc:mysql://3.38.123.173:3306/ssgpoint
    username: ssgpoint
    password: ssgpointdocker
    driver-class-name: com.mysql.cj.jdbc.Driver

JWT:
  SECRET_KEY: f9ee13691cd0a3de2875b5fdcf5babcdb3394a3801e0843d6f998f78b9e016a0
  EXPIRATION_TIME: 14400000
  header: Authorization
  prefix: Bearer


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**