server:
  port: 8000

spring:
  application:
    name: SSGPOINT_APP

  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3307/ssgpoint
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

JWT:
  SECRET_KEY: [시크릿 키]
  EXPIRATION_TIME: 1440000000
  header: Authorization
  prefix: Bearer

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**
